import pandas as pd

# Generate 100 threatening messages
threatening_messages = [
    "You must act now to avoid consequences.",
    "Failure to respond will lead to immediate penalties.",
    "Pay the outstanding balance or face legal action.",
    "Your account will be terminated if you don't comply.",
    "Non-compliance will lead to severe consequences.",
    "We will pursue legal action if you do not cooperate.",
    "Take action now or face further repercussions.",
    "This is your last chance to respond before escalation.",
    "Your account will face penalties without immediate action.",
    "Respond immediately to avoid any negative consequences.",
    "Failure to act will result in account suspension.",
    "This is your final notice before action is taken.",
    "If payment isn’t received, legal proceedings will start.",
    "Ignoring this notice will have serious repercussions.",
    "Further non-compliance will result in penalties.",
    "Legal action is pending if you don’t act now.",
    "Act now to prevent account closure.",
    "Failure to comply will result in immediate action.",
    "We will take action if you do not respond.",
    "This is a critical warning. Act now.",
    "You will regret ignoring this message.",
    "If you don’t respond, there will be penalties.",
    "Ignoring this notice will lead to serious consequences.",
    "Legal action is imminent if you don’t respond.",
    "This matter will be escalated if you don’t act.",
    "If you don’t act now, there will be repercussions.",
    "Failure to respond will result in immediate suspension.",
    "Your account is in jeopardy. Act now.",
    "This is your last chance to avoid penalties.",
    "We require immediate action to prevent escalation.",
    "Further delay will lead to consequences.",
    "Legal proceedings will begin without response.",
    "Failure to comply will lead to serious penalties.",
    "You must act immediately to avoid suspension.",
    "This is a serious warning. Respond now.",
    "Ignoring this will result in negative outcomes.",
    "Legal action will proceed without response.",
    "Act immediately to avoid repercussions.",
    "Immediate action is required to prevent escalation.",
    "If payment isn’t received, further action will be taken.",
    "Your account will face consequences if you do not comply.",
    "This is your last opportunity to avoid penalties.",
    "Failure to respond will lead to further action.",
    "Respond now to avoid legal consequences.",
    "This matter will escalate if you do not act now.",
    "Non-response will result in serious penalties.",
    "Your account is at risk. Immediate action required.",
    "Ignoring this notice will have severe outcomes.",
    "Respond immediately or face penalties.",
    "Failure to act will lead to account suspension.",
    "This is a critical issue. Act immediately.",
    "Failure to comply will result in termination.",
    "If you do not act, there will be consequences.",
    "Non-compliance will lead to escalation.",
    "Act now to prevent further action.",
    "Legal action will proceed without your response.",
    "Failure to respond will have adverse effects.",
    "If you don’t pay now, legal proceedings will start.",
    "This is a serious matter. Do not ignore it.",
    "Legal penalties are imminent without action.",
    "Further delay will lead to penalties.",
    "Act now to prevent escalation.",
    "This is your final notice before penalties.",
    "If you don’t comply, legal action will follow.",
    "Failure to act will result in account suspension.",
    "Immediate response required to avoid action.",
    "If payment is not made, your account will be suspended.",
    "This is a critical warning. Respond now.",
    "Ignoring this will result in penalties.",
    "Failure to respond will result in escalation.",
    "Legal action will be taken if you do not comply.",
    "This matter will escalate without your response.",
    "Your account is in jeopardy. Act immediately.",
    "Further delay will have severe consequences.",
    "Non-response will lead to penalties.",
    "Failure to act will lead to further action.",
    "This is a serious warning. Act now.",
    "Your account will face consequences without response.",
    "Legal action is imminent. Respond now.",
    "This issue will be escalated if you don’t comply.",
    "Immediate action required to avoid suspension.",
    "If you don’t act now, penalties will follow.",
    "Further non-compliance will lead to action.",
    "Your account is at risk. Take action now.",
    "This is a critical issue. Do not ignore it.",
    "Ignoring this message will lead to repercussions.",
    "Immediate action required to prevent termination.",
    "Legal action will proceed without your response.",
    "Failure to respond will result in suspension.",
    "This is a critical warning. Act now.",
    "If payment isn’t made, penalties will apply.",
    "Your account will be impacted if you do not respond.",
    "This is your last warning. Respond now.",
    "Further inaction will lead to serious outcomes.",
    "Act immediately to avoid repercussions.",
    "If you don’t act, legal measures will follow.",
    "Non-response will lead to escalation.",
    "Failure to comply will result in further action.",
]

# Generate 100 non-threatening messages
non_threatening_messages = [
    "Please let us know if you need any assistance.",
    "Feel free to reach out whenever convenient.",
    "You may contact us at your convenience.",
    "If you have any questions, please ask.",
    "Take your time with the response, no rush.",
    "Kindly provide your input when you're ready.",
    "Your feedback is appreciated at any time.",
    "Please follow up when possible.",
    "Take your time, there is no deadline.",
    "Reach out to us whenever it's convenient for you.",
    "There is no immediate action needed from you.",
    "Feel free to contact us if you have any questions.",
    "We would love to hear from you when you’re ready.",
    "Let us know if there’s anything we can assist with.",
    "Please let us know if you need further information.",
    "Your feedback is welcome at any time.",
    "Reach out whenever convenient for you.",
    "You may respond at your earliest convenience.",
    "Please do not rush, take your time.",
    "There is no urgency, feel free to reach out later.",
    "Let us know if you have any questions or concerns.",
    "We appreciate your response when you’re available.",
    "Take your time, there is no deadline.",
    "Your feedback is valuable, whenever you can provide it.",
    "Feel free to contact us if you have further questions.",
    "Please reach out when you have a moment.",
    "Your response is welcome whenever convenient.",
    "Let us know if you need more details.",
    "Take your time, there is no rush.",
    "Please respond when convenient for you.",
    "Feel free to contact us at your earliest convenience.",
    "You may respond when you’re ready.",
    "There is no hurry, please take your time.",
    "Reach out whenever is best for you.",
    "Please follow up when it’s convenient.",
    "No rush, respond when you’re ready.",
    "We are here to assist whenever you need.",
    "Take your time, there’s no deadline.",
    "Feel free to reach out with any questions.",
    "Please let us know if you need any assistance.",
    "There’s no rush, respond when you can.",
    "Feel free to follow up when convenient.",
    "There’s no immediate need to respond.",
    "Take your time, we appreciate your input.",
    "Reach out at your convenience.",
    "Please contact us when ready.",
    "There’s no urgency, feel free to respond later.",
    "Your feedback is welcome at any time.",
    "Feel free to respond whenever you can.",
    "Please take your time, there is no rush.",
    "Contact us at your convenience.",
    "We appreciate your response when convenient.",
    "Please do not rush, take your time.",
    "No need to rush, take your time.",
    "Contact us when you’re ready.",
    "Please feel free to respond at any time.",
    "There is no urgency, respond at your convenience.",
    "We’re happy to assist at any time.",
    "Feel free to reach out whenever you’re ready.",
    "Take your time, there is no hurry.",
    "There’s no rush, please respond when you can.",
    "Please let us know if you need more time.",
    "Feel free to follow up whenever convenient.",
    "We look forward to your feedback at any time.",
    "Take your time, we are in no hurry.",
    "Respond at your earliest convenience.",
    "Feel free to respond at your convenience.",
    "Please contact us when you have time.",
    "No need to rush, take your time.",
    "Your response is welcome whenever you’re ready.",
    "Please let us know if you need further assistance.",
    "Take your time with the response, no rush.",
    "Reach out to us whenever you’re ready.",
    "Please respond when you’re available.",
    "We appreciate your input at any time.",
    "Contact us at your earliest convenience.",
    "Please follow up whenever it’s convenient.",
    "There’s no need to rush, take your time.",
    "Feel free to reach out with questions.",
    "Let us know if you need further information.",
]

# Labels: 1 for threatening, 0 for non-threatening
data = {
    "message": threatening_messages + non_threatening_messages,
    "label": [1] * len(threatening_messages) + [0] * len(non_threatening_messages)
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("threatening_messages_test_data.csv", index=False)
print("CSV file 'threatening_messages_test_data.csv' created successfully.")

